In [1]:
import numpy as np

In [5]:
A = np.random.randint(0, 100, size = (4,3))

In [13]:
A

array([[ 6, 60, 34],
       [63, 71, 36],
       [51, 75, 96],
       [ 6, 55, 13]])

In [12]:
theta = np.array([4, 2, 100])

In [14]:
A @ theta

array([3544, 3994, 9954, 1434])

In [16]:
A[0] @ theta

3544

In [18]:
theta

array([  4,   2, 100])

In [20]:
theta.reshape(-1, 1).shape

(3, 1)

In [21]:
theta.reshape(-1, 1)

array([[  4],
       [  2],
       [100]])

In [25]:
y = np.random.randint(0, 100, 4)

In [26]:
A

array([[ 6, 60, 34],
       [63, 71, 36],
       [51, 75, 96],
       [ 6, 55, 13]])

In [31]:
errors = y - (A @ theta)

In [33]:
errors @ errors

128702219

In [34]:
errors

array([-3475, -3951, -9948, -1433])

In [36]:
-3475*-3475 + -3951*-3951 + -9948*-9948 + -1433*-1433

128702219