# Holdout Sets Lab

### Introduction

In this lesson, we'll see how we can use holdout sets to correct for overfitting.  We'll do so, with the use of one of the datasets built into sklearn, the california housing dataset.

### Loading our Data

Let's begin by loading our dataset from sklearn.

In [142]:
from sklearn.datasets import fetch_california_housing
dataset = fetch_california_housing()

Now the `fetch_california_housing` method returns to us a dictionary like object.  Begin by viewing the keys in our dataset.

In [145]:
# 
# dict_keys(['data', 'target', 'feature_names', 'DESCR'])

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

One of the keys is `DESCR`.  This is the description of the dataset.  Let's print out the first 1000 lines of the description.

In [216]:
# print DESCR here

Ok, now that we have a sense of the data, let's gather our features.  Create a dataframe from the `dataset` in the `data` key, and name the columns the list of names in the `feature_names` from the dataset.  Assign the dataframe to the variable `X`.

In [217]:

X = None

In [154]:
X[:3]

# 	MedInc	HouseAge	AveRooms	AveBedrms	Population	AveOccup	Latitude	Longitude
# 0	8.3252	41.0	6.984127	1.023810	322.0	2.555556	37.88	-122.23
# 1	8.3014	21.0	6.238137	0.971880	2401.0	2.109842	37.86	-122.22
# 2	7.2574	52.0	8.288136	1.073446	496.0	2.802260	37.85	-122.24

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24

Retrieve the target data from the dataset, and store the data in a pandas series.  Assign it to the variable `y`.

In [218]:
y = None

In [156]:
type(y)
# pandas.core.series.Series

pandas.core.series.Series

In [157]:
y[:3]
# 0    4.526
# 1    3.585
# 2    3.521
# dtype: float64

0    4.526
1    3.585
2    3.521
dtype: float64

Ok, now that we have separate our features and targets, let's train a linear regression model.

In [219]:

model = None

# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

> And calculate the score on the linear regression model.

In [159]:
# 0.6062326851998051

0.6062326851998051

### Checking for Overfitting

Let's take a look at the coefficients from our previous model.

In [162]:
model.coef_
# array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
#        -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
       -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01])

There is one for each of the columns.  So one *crude* way to get a sense of what features may not be contributing too much is to sort our columns by the size of the associated coefficients, from largest to smallest.

> We'll improve on this technique for feature importance in future lessons.

Use numpy to do it.  Assign the result to `sorted_cols`.

In [220]:
sorted_cols = None
sorted_cols
# array(['AveBedrms', 'MedInc', 'HouseAge', 'Population', 'AveOccup',
#        'AveRooms', 'Latitude', 'Longitude'], dtype='<U10')

Ok, now this will be our plan.  We'll create eight different datasets.  The first one will only have the feature `AveBedrms`, then the next one will have the features `AveBedrms` and `MedInc`, then the next dataset will add on `HouseAge`, and so on.

Use list comprehension to create a list of 8 dataframes, each one with an additional feature.

In [164]:
feature_datasets = None

In [171]:
len(feature_datasets)
# 8

8

In [167]:
feature_datasets[0][:3]
# 	AveBedrms
# 0	1.023810
# 1	0.971880
# 2	1.073446

AveBedrms
0   1.023810
1   0.971880
2   1.073446

In [169]:
feature_datasets[1][:3]
# 	AveBedrms	MedInc
# 0	1.023810	8.3252
# 1	0.971880	8.3014
# 2	1.073446	7.2574

AveBedrms  MedInc
0   1.023810  8.3252
1   0.971880  8.3014
2   1.073446  7.2574

Ok, now that we have our eight different datasets, we'll use our train each of these datasets on the first `4/5` of the data, and allocate the remaining 20 percent for the test set.

For example, here's how we could do this with just our first dataset.

In [ ]:
training_cutoff = np.int(.8*X.shape[0])
training_cutoff
# 16512.0

In [192]:
LinearRegression().fit(X[:training_cutoff], y[:training_cutoff])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

> Now use list comprehension to loop through each of the feature datasets and train each model.

In [223]:
models = None
# models

Confirm that you did this correctly by taking a look at the coefficients of your models.  There should be only one coefficient in the first model (as you trained on one feature, and two on the second, and so on.

In [195]:
[model.coef_ for model in models]

# [array([-0.08472077]),
#  array([-0.00530241,  0.4078728 ]),
#  array([0.03627788, 0.42396549, 0.01832752]),
#  array([4.41398935e-02, 4.24895746e-01, 1.93896280e-02, 3.70981852e-05]),
#  array([ 4.39572800e-02,  4.24936826e-01,  1.95360434e-02,  4.09593233e-05,
#         -1.21859740e-02]),
#  array([ 1.05174649e+00,  5.36219341e-01,  1.73618921e-02,  2.53744473e-05,
#         -1.17657007e-02, -2.21649954e-01]),
#  array([ 9.71711856e-01,  5.21567608e-01,  1.76671678e-02,  1.93844117e-05,
#         -1.17596405e-02, -2.01479564e-01, -3.98712430e-02]),
#  array([ 7.10267788e-01,  4.47847084e-01,  9.40820722e-03, -1.47053238e-06,
#         -8.81496820e-03, -1.20960919e-01, -4.21714509e-01, -4.29775301e-01])]

[array([-0.08472077]),
 array([-0.00530241,  0.4078728 ]),
 array([0.03627788, 0.42396549, 0.01832752]),
 array([4.41398935e-02, 4.24895746e-01, 1.93896280e-02, 3.70981852e-05]),
 array([ 4.39572800e-02,  4.24936826e-01,  1.95360434e-02,  4.09593233e-05,
        -1.21859740e-02]),
 array([ 1.05174649e+00,  5.36219341e-01,  1.73618921e-02,  2.53744473e-05,
        -1.17657007e-02, -2.21649954e-01]),
 array([ 9.71711856e-01,  5.21567608e-01,  1.76671678e-02,  1.93844117e-05,
        -1.17596405e-02, -2.01479564e-01, -3.98712430e-02]),
 array([ 7.10267788e-01,  4.47847084e-01,  9.40820722e-03, -1.47053238e-06,
        -8.81496820e-03, -1.20960919e-01, -4.21714509e-01, -4.29775301e-01])]

Now let's see how the first model does scores on the training data.

In [198]:
# Select the first model from the list of models and check the score on the training set here

# 0.0014673783785782435

0.0014673783785782435

Now loop through all of the models and find the scores on the training datasets.

In [201]:
training_scores = None
training_scores
# [0.0014673783785782435,
#  0.45236533768477305,
#  0.4939927242376319,
#  0.4952854616280577,
#  0.4983070309325991,
#  0.5305040120758866,
#  0.535449549407038,
#  0.5844329298051016]

[0.0014673783785782435,
 0.45236533768477305,
 0.4939927242376319,
 0.4952854616280577,
 0.4983070309325991,
 0.5305040120758866,
 0.535449549407038,
 0.5844329298051016]

Next calculate the scores for each model on the holdout dataset.

In [205]:
holdout_scores = None

In [206]:
holdout_scores
# [-0.035080253443077636,
#  0.5290087155979699,
#  0.5434340630909426,
#  0.5429317996619257,
#  0.5193319873743043,
#  0.5347415747282829,
#  0.5243752202100567,
#  0.6605140591531988]

[-0.035080253443077636,
 0.5290087155979699,
 0.5434340630909426,
 0.5429317996619257,
 0.5193319873743043,
 0.5347415747282829,
 0.5243752202100567,
 0.6605140591531988]

Ok, now create a trace for the training scores, with the scores on the y axis and the related column on the x axis. 

Do the same for the holdout scores.

In [224]:
# either matplotlib or plotly is fine

> Answer: <img src="./plotly-graph.png" width="80%">

We'll talk more about feature selection in later lessons, but for now, we can see that the holdout score indicates limited benefit by including features like Population, AveOccup, and AveRooms.  Let's try removing these columns, and then see how we do on our training and test datasets.

> Drop the specified columns and assign the resulting dataframe to the variable `X_select`.

In [225]:
X_select = None

In [99]:
X_select[:2]

# MedInc	HouseAge	AveBedrms	Latitude	Longitude
# 0	8.3252	41.0	1.02381	37.88	-122.23
# 1	8.3014	21.0	0.97188	37.86	-122.22

MedInc  HouseAge  AveBedrms  Latitude  Longitude
0  8.3252      41.0    1.02381     37.88    -122.23
1  8.3014      21.0    0.97188     37.86    -122.22

Now let's train one model on these features, just the 80 percent of our training set.

In [208]:
# fit the model on the training data here

# LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

And score the model on the remaining data.

In [211]:

# 0.6710958382245962

0.6710958382245962

### Using SKlearn to Split

Now let's split our data again.  This time, we'll use sklearn's `train_test_split` function.

In [212]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_select, y, test_size = .3, random_state = 1)

In [213]:
model = LinearRegression().fit(X_train, y_train)

In [214]:
model.score(X_test, y_test)

0.5898474184857773