# From Perfect to Not Perfect Lab

### Introduction

In this lab, we'll practice our Python and Numpy skills, while seeing what happens as we introduce error into our model.

### Starting up

Let's say that we want to model the amount of ticket sales of the opening night of a musical artist at Madison Square Garden.  We will assume that we know the underlying or true model, which is the following:

$tickets\_sold = .12*weekly\_music\_streams - 10000$

Begin by creating a vector of 100 feature variables ranging from $200,000$ to $350,000$.  Use numpy's random generator with a seed of 3.  Assign the result to the variable `weekly_streams`.

In [61]:

weekly_streams = None


array([271530, 277049, 248056])

In [62]:
weekly_streams[:3]
# array([271530, 277049, 248056])

array([271530, 277049, 248056])

Then use numpy to create the number of ticket sales for each feature variable according to the model defined above.  The number should be rounded to the nearest integer.

In [63]:
tickets_sold = None

In [65]:
tickets_sold[:3]

Then perform the same calculation using list comprehension in Python.

> No numpy should be used in the below statement.

In [66]:
tickets_sold_py = None

In [11]:
tickets_sold_py[:3]
# [22584.0, 23246.0, 19767.0]

[22584.0, 23246.0, 19767.0]

Ok, now let's fit a a linear regression model called `perfect_model` using the feature and target variables defined above.

> You can use the numpy arrays to do so.

In [12]:

perfect_model = None

Then calculate the score of the model.

In [14]:

# 0.9999999961855224

0.9999999961855224

And also calculate the root mean squared error using sklearn metrics.

In [17]:

# 0.31460270684722097

0.31460270684722097

> We see a small amount of error because we rounded our data above.

### Adding Error

Ok, now let's add some error to our data and see how our model performs.  Initialize error for each observation ranging from negative 3000 to positive 3000.  Use a seed of 2.

In [67]:

random_errors = None
random_errors[:3]
# array([-425, 2704,  606])

array([-425, 2704,  606])

Add the errors to the our target variables using numpy.

In [68]:
tickets_with_errors = None

In [46]:
tickets_with_errors[:3]
# array([22602., 23111., 19689.])

array([22159., 25950., 20373.])

Now let's see how our previously trained model performs when our new `tickets_with_errors` data.  Calculate the score for with the new data.

In [47]:

# 0.8906120056548548

0.8906120056548548

Now plot both the model's predictions and the data with error matplotlib.

In [69]:
# 

> Answer: <img src="./minor-error.png" width="50%">

Now let's see how our model performs if we increase the error from between -3000 to 3000, to -5000 to 5000.  Assign the new targets to `tickets_larger_error`.

In [56]:


tickets_larger_error = None

# array([24920., 20821., 21404.])

array([24920., 20821., 21404.])

Calculate the score.

In [54]:

# 0.7853455211240589

0.7853455211240589

So we can see that the larger the built in random error, the lower the score.  And there is nothing we can do about it.

Then, once again, plot the model's predictions along side the new `tickets_larger_error` data.

> Answer: <img src="./larger-error.png" width="50%">

So the predictions are the same, it's just the data. that has more error in it.

### Bonus

You likely generated the `tickets_larger_error` in numpy.  Try adding the error to each target variable, this time with list comprehension.

In [60]:
np.random.seed(2)
larger_errors = np.random.randint(-5000, 5000, 100)

tickets_larger_errors = None
tickets_larger_errors[:3]
# [24920.0, 20821.0, 21404.0]

[24920.0, 20821.0, 21404.0]